### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by AndrewSB** [iCepa/iCepa#1]
Hey Conrad,

Was checking out the project, was having issues setting up the project.
1. You've included the Tor.framework as a submodule and through Carthage. Was that Intentional?
2. Build script for lipo is failing. It's assuming that libtun2tor.a has been built, but it appears that it is not the case? (`/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: can't open input file: target/x86_64-apple-ios/release/libtun2tor.a (No such file or directory`)

**Comment by conradev** [comment]
1. Yes, that is [intentional](https://github.com/Carthage/Carthage#using-submodules-for-dependencies), so that I can work on the framework simultaneously
2. I forgot to include this in the `README`, but you need a version of `rustc` that can compile for iOS. If you were to look at the full build log (`⌘-7`), you would probably see an error along those lines.

I will put a guide on how to compile Rust for iOS in the `README`

**Comment by conradev** [comment]
I added the Rust setup guide in https://github.com/iCepa/iCepa/commit/520b63087c66f27847ae4fbd3b832eaf1e96834d to the `README` – could you try it out and see if it works for you?

If you have trouble following along, I'm open to suggestions!

**Comment by AndrewSB** [comment]
Thanks Conrad,

I'm going to take a look tomorrow. Really love what you're trying to build

**Comment by AndrewSB** [comment]
I had an error setting up multirust, I commented on the diff

**Comment by conradev** [comment]
Going to close this issue now that the Rust instructions are greatly simplified!

**Comment by AndrewSB** [comment]
👌
