### ISSUE TITLE
Memory Issue

### ISSUE THREAD

**Issue by eitan1990** [iCepa/iCepa#2]
You mentioned in the README file that
> Tor currently exceeds the 5 MB memory limit set on packet provider extensions by Apple (TODO: File radar). Until this is fixed, iCepa's extension will crash. If you have a jailbroken device, you can circumvent this with jetsamctl. Possible solutions include increasing the use of memory mapping in tor.

In what way did you see this?
I'm developing a Packet Provider extension of my own and seeing my extension crash with "Message from debugger: Terminated due to memory issue". Is this what you see in your extension? 
Also, how do you know the memory limit is 5MB?

Thanks!

**Comment by conradev** [comment]
The Jetsam memory limits are stored in a file named `/System/Library/LaunchDaemons/com.apple.jetsamproperties.XXX.plist` on the iOS filesystem. They are 5 MB on some systems, and 6 MB on systems with more memory (like the iPad Pro).

`Message from debugger: Terminated due to memory issue` is definitely the error you see when Jetsam kills your extension.

**Comment by yarshure** [comment]
if PacketTunnelProvider use Swift ,memory can use 14MB about (my test ,2GB memory iOS device)
