### ISSUE TITLE
Is there any way that Apple will allow this to on the App Store?  

### ISSUE THREAD

**Issue by cwoloszynski** [iCepa/iCepa#21]
Is this a project that could lead to an App Store VPN for TOR or will Apple reject it?

**Comment by ebelinski** [comment]
As far as I understand, it has a good shot. Apple has shown no opposition to apps that use Tor (such as Onion Browser, etc). I also don't think there are fundamental differences between Tor and VPNs that would cause Apple to accept VPN apps but reject iCepa.

**Comment by mehranrasulian** [comment]
So what is the purpose of this project? Is there any build for it?

**Comment by Baccount** [comment]
This app routes all iOS traffic through tor, and you will have to Manually build it right now until it is finished and it will likely be published in the App Store.
https://github.com/iCepa/iCepa#building

**Comment by tladesignz** [comment]
@Baccount, thanks for clarifying!

Actually, in the current situation, it doesn't make sense to release this software, since it is not stable. This is mainly due to the fact, that Network Extensions aren't allowed to consume more than 15 MByte of non-disk-backed memory.
This constraint leads to the termination of the Network Extension after about 2 minutes of operation.

We're currently working with the Tor Project to figure out a way to make Tor be compliant with this constraint. But this will take a while (months), since it will need some re-organisation of the Tor code.

You will recognize progress on this project then, but for now, the work on it is basically suspended.

I close this thread now, because I don't consider this an "issue". Feel free to reopen, if you have any contribution or actual question.

**Comment by mehranrasulian** [comment]
I am living in Iran. And the government these days has limited the peoples from accessing all the popular VPN’s. Because of that there was a good potential for your app to be popular in Iran. anyway, keep the good job up 👏

**Comment by Baccount** [comment]
You can download the source for OnionBrowser https://github.com/mtigas/OnionBrowser and side load it on your IOS device. Version 2 of OnionBrowser will be a very large update.
https://itunes.apple.com/us/app/onion-browser/id519296448?mt=8

**Comment by tladesignz** [comment]
We are very short of releasing OnionBrowser 2 - in fact, I'm expecting it for this month!
That one will still have the issue, that Tor's connections cannot be rebuilt after you shut down your device, but it will have a better browser UI. (Also working with Tor project on that issue.)

I strongly advise against using iCepa or any other Network Extension (aka. "VPN") app like Psiphon or Shadowsocks in situations, where things you do on the net can bring you in more than minor legal trouble.

Apple has unfortunately designed this feature with a soft fail behaviour. So, if the VPN connection breaks for whatever reason, but not the general network connection, currently ongoing requests will immediately be resent over the normal connection!

Use only specific apps like Onion Browser, which will *only* connect over Tor and don't have this soft fail behaviour built in!

BTW: Even if we manage to get iCepa working stable, we will most probably never be able to add bridging with Meek or OBSF4 due to the memory constraint, as long as Apple isn't increasing the 15 MB limit.

**Comment by tladesignz** [comment]
Ah... and: Thanks for the kudos!
