### ISSUE TITLE
Build failed with Use of unresolved identifier 'tun2tor_run'

### ISSUE THREAD

**Issue by simform-solutions** [iCepa/iCepa#35]
I have installed rustup and all the stuff that needed to run the code. But while building I got this kind of error in my project.
can you please help?
![Screenshot 2020-11-06 at 5 07 03 PM](https://user-images.githubusercontent.com/8736329/98362516-5a0b5a80-2053-11eb-8497-256ef544160b.png)

**Comment by tladesignz** [comment]
That means that tun2tor didn't build. Check Xcode's Report Navigator. That shows you the full build output.

However, the last time I tried, I couldn't build it anymore, because the code was too old and can't be built with newer Rust versions.

Good luck! And keep us posted what you had to do to get it built!

**Comment by simform-solutions** [comment]
@tladesignz  can you share the required Rust Version for successfully build this repository?

**Comment by tladesignz** [comment]
@simform-solutions, please cross-check yourself: Take commit timestamps of main part of tun2tor, compare with Rust releases. Or just work your way back through Rust main versions.
