### ISSUE TITLE
Name it just 'Cepa'

### ISSUE THREAD

**Issue by butter-radish** [iCepa/iCepa#41]
It's a subjective, fickle thing—but I personally find just 'Cepa' to be a better name for this project than prefixing it with 'i-' like iOS apps did a decade ago. Seems dated.

I'm really happy you folks made headway with getting this working on iOS! Can't wait to try it out when it makes it onto the App Store.

**Comment by tladesignz** [comment]
You aren't seriously suggesting that, do you? Of course we won't change the name. It's treaded in.

Anyway, thanks a lot for the rest of your feedback! Always good to hear, that people are interested. 

Watch out for "Orbot" on the app store. Will take some more weeks, because we have to work over a few obstacles, Apple threw in our way, but then...
