### ISSUE TITLE
Error: Could not start manager: Error Domain=NEVPNErrorDomain Code=1 "(null)"

### ISSUE THREAD

**Issue by ghazel** [iCepa/iCepa#9]
On macOS

```
iCepa[44972:615295] Error: Could not start manager: Error Domain=NEVPNErrorDomain Code=1 "(null)"
```

(There are quite a few Swift 3 errors getting iCepa to run, but I believe I resolved them all correctly...)

**Comment by ghazel** [comment]
I managed to resolve this error by calling `loadFromPreferences` after `saveToPreferences` succeeded, before calling `startVPNTunnel`.

**Comment by ghazel** [comment]
i.e.

```swift
saveToPreferences {
  loadFromPreferences {
    connection. startVPNTunnel()
  }
}
```

**Comment by conradev** [comment]
Hi @ghazel, thanks for checking iCepa out! I have since updated it to Swift 3, and made some other improvements.

That was an issue I noticed as well. The configuration becomes stale after saving it, which we need to do in order enable the configuration if it is disabled. Would you like to submit a patch? If not, I can definitely work on it!

**Comment by vikivae** [comment]
Hi@ghazel, could you tell me how to solve this problem on mac osx? thank you!

**Comment by mukeshlokare** [comment]
Can anybody tell me the resolve for this issue ? I have tried ghazel solution but i am getting Optional(Error Domain=NEVPNErrorDomain Code=4 "(null)")
